### ISSUE TITLE
Still cannnot add engine on MacOS en-croissant v2.1?

### ISSUE THREAD

**Issue by kenpchess** [franciscoBSalgueiro/en-croissant#3]
Hello again. I still cannot add an engine on MacOS en-crossaint new version v2.1.  I go to -engines-add-local-click-in-the-binary-field and all engine binaries are still greyed out. Am I missing some option?

Also although I could download Komodo under -engines-download it will never actually start (no err msg, nothing) if I select it to play against as an engine or for analysis. . So I really cannot test ANY of the play or analysis features on MacOS!

Thanks in advance. - kenpchess

**Comment by franciscoBSalgueiro** [comment]
I believe this should fix the local engines, but probably not the Komodo issue. Are you running on an Intel or M1/M2 mac?

**Comment by kenpchess** [comment]
(duplicate of email info for github record) 

Hello Fransisco! Yes, making progress! Local engines are now addable and can be played against. Very nice. Yes, unfortunately downloaded Komodo is still not working. I am running an 2018-2020 Intel 3.6 ghz quad-core i3 mac-mini with 24gb of memory and currently on MacOs Big Sur 11.7.2.

Also to add to your ToDo list, I am having trouble getting previously added databases to list their games (spinner keeps spinning). I am going to try adding new pgn database and see what happens.

Also I noticed a GUI glitch that after playing a game against an engine I cannot get the home screen or play screen to re-display properly (just blank). It appears some user interface element is not getting reset properly.

Also just a suggestion, but I would add in some various progress displays (more than just the spinner) when databases, etc. are loading, analysis game report is being created, etc.

But I really like your minimalist GUI in general. I think once you squash most of your bugs and crank out a couple of versions you will have a real nice product!

By the way, I still have not found much info on Tauri for Mac, if you ever get a chance to investigate I would really like some more build info for macos!

Thanks for your hard work. Looks very promising... - kenpchess
